name: llegaexpress
description: Llega App Express

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  enough_convert: ^1.6.0
  barcode_scan2: ^4.2.1
  url_launcher: ^6.1.2
  webview_flutter: ^3.0.4
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/logos/
    - images/icons/
    - images/backgrounds/
    - assets/
    - .env